import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { QueryProvider } from "../providers";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.ttf",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <QueryProvider>
        <body className={`${pretendard.variable}`}>{children}</body>
      </QueryProvider>
    </html>
  );
}
